name: Setup xcode
description: 'Set up your GitHub Actions workflow with a specific version of xcode'
inputs:
  xcode-version:
    description: 'The xcode version to use'
    required: false
    default: '16.4.0'
runs:
  using: "composite"
  steps:
    - name: Setup xcode
      uses: maxim-lobanov/setup-xcode@7f352e61cbe8130c957c3bc898c4fb025784ea1e
      with:
        xcode-version: ${{ inputs.xcode-version }}
